"""Add message and thread connections

Revision ID: 555d92499f4a
Revises: c6e07d15161c
Create Date: 2020-09-14 19:59:34.214397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555d92499f4a'
down_revision = 'c6e07d15161c'
branch_labels = None
depends_on = None


def upgrade():
    # ### Upgrade strategy:
    # 1. Add columns as nullable
    # 2. Populate with base value (1), which should be created before this
    # 3. Set columns as non-nullable

    op.add_column('messages', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'threads', ['thread_id'], ['id'])
    op.execute("UPDATE messages SET thread_id = 1")
    op.alter_column('messages', 'thread_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'thread_id')
    # ### end Alembic commands ###
