"""Re-initialize databases

Revision ID: c16e8ce10ca9
Revises: 
Create Date: 2020-09-15 15:04:22.433921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c16e8ce10ca9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("content_filename", sa.String(), nullable=False),
        sa.Column("thread_id", postgresql.UUID(), nullable=False),
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("threads")
    # ### end Alembic commands ###
