version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  test_database:
    image: "postgres"
    environment:
      - POSTGRES_USER=nois_test
      - POSTGRES_PASSWORD=nois_test
      - POSTGRES_DB=nois_test
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  data:
