version: "3.8"
services:
  database:
    image: edgedb/edgedb:1-alpha6
    volumes:
      - edgedb-data:/var/lib/edgedb/data
    ports:
      - "5656:5656"
      - "8888:8888"

volumes:
  edgedb-data:
