name: "App: Code style check"
on:
  push:
    paths:
      - 'app/**'
      - '!app/**/*.md'

jobs:
  code_style_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nois-app
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install deps
        run: |
          yarn install --frozen-lockfile
      - name: Run code style check
        run: |
          yarn lint
